name: my demo flow
on: workflow_dispatch

jobs:
  my_first_job:
    environment:
      name: Production      
    runs-on: ubuntu-slim    
    steps:
      - name: my steps of job1        
        run: |
          echo "------org level------"
          echo "${{vars.ORG_VAR}}"
          echo "${{secrets.SECRETE_ORG_VAR}}"
          echo "------------"
          echo "------repo level------"
          echo "${{vars.REPO_VAR}}"
          echo "${{secrets.SECRETE_REPO_VAR}}"
          echo "------------"
          echo "------environment i,e production level------"
          echo "${{vars.PROD_VAR}}"
          echo "${{secrets.PROD_SECRETE_VAR}}"
          echo "------------"
